---
- name: Include OS-specific vars
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure baseline packages present 
  ansible.builtin.package:
    name: "{{ packages_base }}"
    state: present

- name: Accounts and Password policy
  include_tasks: accounts.yml
  tags: ['accounts']

- name: Configure SSH 
  include_tasks: ssh.yml
  tags: ['ssh']

- name: Configure auditd
  include_tasks: auditd.yml
  tags: ['auditd']

- name: Kernel/network sysctl
  include_tasks: sysctl.yml
  tags: ['sysctl']

- name: Filesystem permissions & special bits
  include_tasks: filesystem.yml
  tags: ['filesystem']

- name: Services & firewall
  include_tasks: services.yml
  tags: ['services']
